services:
  hostel-api:
    image: vattamrajesh/hostelmanagement:latest
    ports:
      - "8085:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ConnectionStrings__DefaultConnection: "Server=hostel-db;Database=HostelManagement;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True;"
    depends_on:
      - hostel-db
    networks:
      - hostel-network

  hostel-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - hostel-network

networks:
  hostel-network:
