services:
  hostel-api:
    image: vattamrajesh/hostelmanagement:latest
    ports:
      - "8085:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
    depends_on:
      - hostel-db-main
    networks:
      - hostel-main-network

  hostel-db-main:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1450:1433"
    volumes:
      - hostel_main_db_data:/var/opt/mssql
    networks:
      - hostel-main-network

networks:
  hostel-main-network:

volumes:
  hostel_main_db_data:
