services:
  hostel-api:
    image: vattamrajesh/hostelmanagement:latest
    ports:
      - "8085:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
    depends_on:
      - hostel-db
    networks:
      - hostel-network

  hostel-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - hostel-network

networks:
  hostel-network:
